version: '3.3'

services:
  app:
    build: 
      context: .
      args:
      - PYTHON_VERSION=${PYTHON_VERSION}
      - USERNAME=${APP_USERNAME}
      - USER_UID=${APP_GROUP_UID}
      - APP_PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:5000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .flaskenv

  db:
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

